let runner = TestRunner()
runActivityCoordinatorTests(runner)
runPillGeometryTests(runner)
runModuleTests(runner)
runAudioOutputTests(runner)
runHUDTests(runner)
runShelfTests(runner)
runTransformTests(runner)
runTransformRunnerTests(runner)
runWidgetTests(runner)
runCalendarPrivacyTests(runner)
runner.finish()
